spring:
  profiles:
    active: local
mybatis:
  config-location: classpath:mybatis-config.xml
  check-config-location: true
---
spring:
  profiles: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example
    username: example
    password: example
---
spring:
  profiles: devevelopment
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example
    username: example
    password: example
---
spring:
  profiles: production
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example
    username: example
    password: example
